//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExecutionPlane
    {
        public int IdExecution { get; set; }
        public int IdPlane { get; set; }
        public bool Active { get; set; }
    
        public virtual Execution Execution { get; set; }
    }
}
